Repository kubernetes-sigs/container-object-storage-interface-spec, pull requests merged in 2020-12, with the labels that each got.

#10 Removing subtree check as release tools no longer a git subtree but c…
  release-tools/build.make
Labels: approved, cncf-cla: yes, lgtm, size/S

#11 Fix go.mod module name
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13 Added fake client
  fake/cosi.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#15 updated README.md and added spec.md
  README.md
  spec.md
Labels: approved, cncf-cla: yes, lgtm, size/M
