Repository kubernetes-sigs/container-object-storage-interface-spec, pull requests merged in 2022-08, with the labels that each got.

#38 Update the code with latest KEP
  Makefile
  cosi.pb.go
  cosi.pb.json.go
  cosi.proto
  fake/cosi.pb.fake.go
  go.mod
  go.sum
  spec.md
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#39 Update go version in release tools
  release-tools/travis.yml
Labels: cncf-cla: yes, size/XS

#40 update kubernetes version to v1.24.0
  release-tools/prow.sh
Labels: cncf-cla: yes

#41 Create CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.1.md
Labels: cncf-cla: yes
